options:
  oxTkeystore-pass:
    type: string
    default: "passpass"
    description: "default password for keystore-pass"
  oxTmysql-pass:
    type: string
    default: "passpass"
    description: "default password for mysql-pass"
  oxTvdsldap-pass:
    type: string
    default: "passpass"
    description: "default password for vdsldap-pass"
  oxTidpldap-pass:
    type: string
    default: "passpass"
    description: "default password for idpldap-pass"
  oxTidpsecuritykey-pass:
    type: string
    default: "passpass"
    description: "default password for idpsecuritykey-pass"
  org-inum:
    type: string
    default: "@!1111"
    description: "org inum"
  display-name:
    type: string
    default: "Test server"
    description: "display name"
  org-iname:
    type: string
    default: "@test*org"
    description: "org iname"
  org-short-name:
    type: string
    default: "test"
    description: "org short name"
  appliance-iname:
    type: string
    default: "@test*appliance"
    description: "appliance Iname"
  web-keys:
    type: string
    default: ""
    description: "oxauth web-keys json file base64 encoded"
  py-id-gen:
    type: string
    default: ""
    description: "oxauth id-gen py file base64 encoded"
